### ISSUE TITLE
Add support for iterations

### ISSUE THREAD

**Issue by cmbuckley** [brucemcpherson/SankeySnip#1]
The [configuration options for Sankey diagrams](https://developers.google.com/chart/interactive/docs/gallery/sankey#configuration-options) includes an `iterations` option, which can be used to increase the number of node layouts that the D3 engine attempts. This could be used to tweak the readability of complex Sankey diagrams.

**Comment by brucemcpherson** [comment]
I'm not maintaining this app any more, but feel free to clone and modify - the options can be found in sankey.gs
